# Generated by Django 2.0.4 on 2018-11-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resturnant',
            new_name='Restaurant',
        ),
    ]
